script: ./compile.sh && npm run doctest
after_success: "[[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]] && bash ./deploy.sh"
env:
  global:
  - GH_REF: git@github.com:tuzhu008/momentjs_cn.git
language: node_js
node_js:
- 5
